server:
  port: 4799
  servlet:
    context-path: /zfile
  tomcat:
    max-http-form-post-size: 104857600MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxxxxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: warn
    com.inet: debug
  file:
    path: log/zfile.log
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
mail:
  host: smtp.xxx.com
  port: 465
  from: xxx@qq.com
  user: xxx@qq.com
  pass: xxxxxxx



